channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - pandas==1.1.5
  - azureml-defaults
  - joblib==0.17.0
- scikit-learn==0.23.2
name: azureml_2d0fd20031db3baaed8684d5f08fe619
